#!/usr/bin/python3

import sys

if len(sys.argv) == 1:
    print('0 arguments.')
elif len(sys.argv) == 2:
    print('1 argument:')
    print(f'1: {sys.argv[1]}', end=' ')
else:
    print(f'{len(sys.argv)} arguments:', end='')
    for i, arg in enumerate(sys.argv[1:]):
        print(f'{i}: {arg}', end='')
